### ISSUE TITLE
היי

### ISSUE THREAD

**Issue by eilon40** [DanielSparta/FXP-security-vulnerabilities-That-i-found#1]
הבנתי שחלק מהפרצות תוקנו

מוזמן לבדוק שוב ולעדכן תודה!

**Comment by DanielSparta** [comment]
שום דבר לא תוקן.

**Comment by eilon40** [comment]
> שום דבר לא תוקן.

בדקתי שוב זה תוקן
https://user-images.githubusercontent.com/111179755/250377094-c7f79750-8c42-4770-ad30-5fcaa9d55a87.png
ולא פועל יותר

**Comment by DanielSparta** [comment]
זה לא תוקן. תקרא את הmanual שוב, השתדלתי לרשום די בבירור:

![image](https://github.com/DanielSparta/FXP-security-vulnerabilities-That-i-found/assets/111179755/d49193e9-595f-4174-b772-4342d945034d)
אתה תצטרך שהצד השני יהיה באותו חלון איתך. לא לבצע רענון לעמוד, תפתח למשל 2 כרטיסיות על אותו הצאט ורק אז תלחץ על 3 נקודות


אם עדיין לא עובד לך תצטרך לקרוא את הקוד באתר
